services:
  # victim:
  #   build:
  #     context: ./victim
  #   container_name: victim
  #   ports:
  #     - 8080:80
  apache-victim:
    build:
      context: ./apache-victim
    container_name: apache-victim
    ports:
      - 8080:80

  attacker:
    build: 
      context: ./attacker
    container_name: attacker 
    network_mode: "host"
  
