services:
  # victim:
  #   build:
  #     context: ./victim
  #   container_name: victim
  #   ports:
  #     - 8080:80
  weak-victim:
    build:
      context: ./weak-victim
    container_name: weak-victim
    ports:
      - 8080:3000

  attacker:
    build: 
      context: ./attacker
    container_name: attacker 
    network_mode: "host"
  
